#!/usr/bin/env python3
"""生成 Ghostty GX 界面的 zh-CN 翻译表 src/gx/i18n/zh_CN.zig。

用法：
  python scripts/gx_i18n.py            重新生成并写入（内容不变时不改文件）
  python scripts/gx_i18n.py --check    只读校验：已提交的翻译表与源文件不一致时退出 1
  可选 --root PATH（测试用，默认取脚本所在仓库）

来源（后者覆盖前者）：
  1. 上游 po/zh_CN.po：GTK 界面已有的译文；
  2. fork 的 src/gx/i18n/gx.zh_CN.po：Ghostty GX 新增与改写的译文，后续 UI 任务往这里追加。
合并规则：跳过文件头（msgid ""）、`#, fuzzy` 条目、`#~` 废弃条目与空译文；带 msgctxt 的
条目以 gettext 的 `<msgctxt>\\x04<msgid>` 为键（Zig 侧用 trCtx 查询），不影响无上下文的同名
条目；复数条目取 msgstr[0]（zh_CN 只有一种复数形式），msgid 与 msgid_plural 都作为键，
msgid_plural 不覆盖同名的单数条目。同一文件内键重复、fork 条目的 `{name}` 占位符与原文
不一致、语法错误都会以退出码 2 报错。

输出确定：按键的 UTF-8 字节序排序、键唯一、LF、无时间戳，同一输入在任何平台得到同样的字节；
CRLF 检出的 .po 与翻译表视同 LF。退出码：0 成功（或 --check 时翻译表新鲜）；1 --check 时
翻译表缺失或过期；2 用法错误、源文件缺失或不合法。
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
UPSTREAM_PO = "po/zh_CN.po"
FORK_PO = "src/gx/i18n/gx.zh_CN.po"
OUTPUT = "src/gx/i18n/zh_CN.zig"
CONTEXT_SEPARATOR = "\x04"
PLACEHOLDER_RE = re.compile(r"\{([A-Za-z_][A-Za-z0-9_]*)\}")
KEYWORD_RE = re.compile(r"^(msgctxt|msgid_plural|msgid|msgstr(?:\[(\d+)\])?)\s+(\".*)$")
ESCAPES = {
    "n": "\n",
    "t": "\t",
    "r": "\r",
    "a": "\a",
    "b": "\b",
    "f": "\f",
    "v": "\v",
    "\\": "\\",
    '"': '"',
    "'": "'",
    "?": "?",
}
HEADER = """\
//! zh-CN translations for the Ghostty GX user interface.
//!
//! Generated by `python scripts/gx_i18n.py` from `po/zh_CN.po` and
//! `src/gx/i18n/gx.zh_CN.po` (fork entries win). Do not edit by hand:
//! add or change translations in `src/gx/i18n/gx.zh_CN.po` and regenerate.
//! `python scripts/gx_i18n.py --check` fails when this file is stale.

/// A translation keyed by msgid, or by `msgctxt ++ "\\x04" ++ msgid` for
/// entries with a context. Entries are sorted by key bytes and unique.
pub const Entry = struct {
    key: [:0]const u8,
    msgstr: [:0]const u8,
};

pub const entries = [_]Entry{
"""
FOOTER = "};\n"


class PoError(ValueError):
    """A .po file that cannot be parsed or merged."""


@dataclass
class PoEntry:
    line: int
    flags: set[str] = field(default_factory=set)
    obsolete: bool = False
    msgctxt: str | None = None
    msgid: str | None = None
    msgid_plural: str | None = None
    msgstr: dict[int, str] = field(default_factory=dict)

    def key(self) -> str:
        assert self.msgid is not None
        if self.msgctxt is None:
            return self.msgid
        return f"{self.msgctxt}{CONTEXT_SEPARATOR}{self.msgid}"

    def plural_key(self) -> str | None:
        if self.msgid_plural is None:
            return None
        if self.msgctxt is None:
            return self.msgid_plural
        return f"{self.msgctxt}{CONTEXT_SEPARATOR}{self.msgid_plural}"


def decode_string(literal: str, where: str) -> str:
    """Decode one double-quoted .po string literal (the quotes included)."""
    literal = literal.strip()
    if len(literal) < 2 or literal[0] != '"' or literal[-1] != '"':
        raise PoError(f"{where}: expected a double-quoted string, got {literal!r}")
    body = literal[1:-1]
    out: list[str] = []
    i = 0
    while i < len(body):
        char = body[i]
        if char == '"':
            raise PoError(f"{where}: unescaped double quote inside {literal!r}")
        if char != "\\":
            out.append(char)
            i += 1
            continue
        if i + 1 >= len(body):
            raise PoError(f"{where}: dangling backslash in {literal!r}")
        nxt = body[i + 1]
        if nxt in ESCAPES:
            out.append(ESCAPES[nxt])
            i += 2
        elif nxt in "01234567":
            digits = re.match(r"[0-7]{1,3}", body[i + 1:]).group(0)
            out.append(chr(int(digits, 8)))
            i += 1 + len(digits)
        elif nxt == "x":
            digits = re.match(r"[0-9A-Fa-f]{1,2}", body[i + 2:])
            if digits is None:
                raise PoError(f"{where}: bad \\x escape in {literal!r}")
            out.append(chr(int(digits.group(0), 16)))
            i += 2 + len(digits.group(0))
        else:
            raise PoError(f"{where}: unknown escape \\{nxt} in {literal!r}")
    return "".join(out)


def parse_po(text: str, name: str) -> list[PoEntry]:
    """Parse gettext .po text into entries (obsolete `#~` entries are flagged, not dropped)."""
    entries: list[PoEntry] = []
    current = PoEntry(line=1)
    # The field that continuation lines ("...") append to: (kind, plural index).
    target: tuple[str, int] | None = None

    def finish() -> None:
        nonlocal current, target
        if current.msgid is not None:
            if not current.msgstr:
                raise PoError(f"{name}:{current.line}: entry has no msgstr")
            entries.append(current)
        elif current.msgctxt is not None or current.msgstr:
            raise PoError(f"{name}:{current.line}: entry has no msgid")
        target = None

    def append(where: str, value: str) -> None:
        kind, index = target  # type: ignore[misc]
        if kind == "msgstr":
            current.msgstr[index] += value
        else:
            setattr(current, kind, getattr(current, kind) + value)

    for number, raw in enumerate(text.splitlines(), start=1):
        where = f"{name}:{number}"
        line = raw.strip()
        obsolete = False
        if line.startswith("#~"):
            obsolete = True
            line = line[2:].strip()
            if not line or line.startswith("|"):
                continue
        elif line.startswith("#"):
            if current.msgstr:
                finish()
                current = PoEntry(line=number)
            if line.startswith("#,"):
                current.flags.update(flag.strip() for flag in line[2:].split(",") if flag.strip())
            continue
        if not line:
            if current.msgstr:
                finish()
                current = PoEntry(line=number)
            continue
        if obsolete:
            if current.msgid is not None and current.msgstr and not current.obsolete:
                finish()
                current = PoEntry(line=number)
            current.obsolete = True
        if line.startswith('"'):
            if target is None:
                raise PoError(f"{where}: string continuation without a keyword")
            append(where, decode_string(line, where))
            continue
        match = KEYWORD_RE.match(line)
        if match is None:
            raise PoError(f"{where}: cannot parse line {raw!r}")
        keyword, index, literal = match.group(1), match.group(2), match.group(3)
        value = decode_string(literal, where)
        if keyword in ("msgctxt", "msgid") and (current.msgstr or (keyword == "msgctxt" and current.msgid is not None)):
            finish()
            current = PoEntry(line=number, obsolete=obsolete)
        if keyword == "msgctxt":
            if current.msgctxt is not None or current.msgid is not None:
                raise PoError(f"{where}: unexpected msgctxt")
            current.msgctxt = value
            target = ("msgctxt", 0)
        elif keyword == "msgid":
            if current.msgid is not None:
                raise PoError(f"{where}: msgid without a preceding msgstr")
            current.msgid = value
            current.line = number
            target = ("msgid", 0)
        elif keyword == "msgid_plural":
            if current.msgid is None or current.msgid_plural is not None:
                raise PoError(f"{where}: unexpected msgid_plural")
            current.msgid_plural = value
            target = ("msgid_plural", 0)
        else:
            if current.msgid is None:
                raise PoError(f"{where}: msgstr without msgid")
            plural_index = int(index) if index is not None else 0
            if (index is None) != (current.msgid_plural is None):
                raise PoError(f"{where}: msgstr form does not match msgid_plural")
            if plural_index in current.msgstr:
                raise PoError(f"{where}: duplicate msgstr[{plural_index}]")
            current.msgstr[plural_index] = value
            target = ("msgstr", plural_index)
    finish()
    return entries


def table_from(entries: list[PoEntry], name: str) -> dict[str, str]:
    """Usable translations of one .po file: key -> msgstr."""
    table: dict[str, str] = {}
    lines: dict[str, int] = {}
    plurals: list[tuple[str, str]] = []
    for entry in entries:
        if entry.obsolete or "fuzzy" in entry.flags:
            continue
        if entry.msgid == "" and entry.msgctxt is None:
            continue
        msgstr = entry.msgstr.get(0, "")
        if not msgstr:
            continue
        key = entry.key()
        if key in table:
            raise PoError(f"{name}:{entry.line}: duplicate msgid {key!r} (first on line {lines[key]})")
        table[key] = msgstr
        lines[key] = entry.line
        plural = entry.plural_key()
        if plural is not None:
            plurals.append((plural, msgstr))
    for plural, msgstr in plurals:
        table.setdefault(plural, msgstr)
    return table


def placeholder_problems(table: dict[str, str], name: str) -> list[str]:
    problems = []
    for key, msgstr in sorted(table.items()):
        msgid = key.split(CONTEXT_SEPARATOR, 1)[-1]
        expected = sorted(PLACEHOLDER_RE.findall(msgid))
        actual = sorted(PLACEHOLDER_RE.findall(msgstr))
        if expected != actual:
            problems.append(f"{name}: placeholders of {msgid!r} {expected} do not match {msgstr!r} {actual}")
    return problems


def merge(upstream: dict[str, str], fork: dict[str, str]) -> dict[str, str]:
    merged = dict(upstream)
    merged.update(fork)
    return merged


def zig_string(value: str) -> str:
    out = ['"']
    for char in value:
        code = ord(char)
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif code < 0x20 or code == 0x7F:
            out.append(f"\\x{code:02x}")
        elif 0x80 <= code <= 0x9F or code in (0x2028, 0x2029, 0xFEFF):
            out.append(f"\\u{{{code:x}}}")
        else:
            out.append(char)
    out.append('"')
    return "".join(out)


def sort_key(key: str) -> bytes:
    return key.encode("utf-8")


def render(table: dict[str, str]) -> str:
    lines = [HEADER]
    for key in sorted(table, key=sort_key):
        lines.append(f"    .{{ .key = {zig_string(key)}, .msgstr = {zig_string(table[key])} }},\n")
    lines.append(FOOTER)
    return "".join(lines)


def read_po(root: Path, rel: str) -> list[PoEntry]:
    path = root / rel
    try:
        text = path.read_text(encoding="utf-8-sig")
    except FileNotFoundError:
        raise PoError(f"{rel} is missing") from None
    except UnicodeDecodeError as err:
        raise PoError(f"{rel} is not valid UTF-8: {err}") from None
    return parse_po(text, rel)


def build(root: Path) -> str:
    """Return the generated Zig source for the repository at ``root``."""
    upstream = table_from(read_po(root, UPSTREAM_PO), UPSTREAM_PO)
    fork = table_from(read_po(root, FORK_PO), FORK_PO)
    problems = placeholder_problems(fork, FORK_PO)
    if problems:
        raise PoError("\n".join(problems))
    return render(merge(upstream, fork))


def normalize(text: str) -> str:
    return text.replace("\r\n", "\n")


def _utf8_stdio() -> None:
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8", errors="replace")


def main(argv: list[str] | None = None) -> int:
    _utf8_stdio()
    parser = argparse.ArgumentParser(
        description="生成 src/gx/i18n/zh_CN.zig（Ghostty GX zh-CN 翻译表）",
    )
    parser.add_argument("--check", action="store_true", help="只校验翻译表是否新鲜，不写入")
    parser.add_argument("--root", type=Path, default=REPO_ROOT, help="仓库根目录（测试用）")
    args = parser.parse_args(argv)

    root: Path = args.root
    try:
        generated = build(root)
    except PoError as err:
        print(f"[gx-i18n] {err}", file=sys.stderr)
        return 2

    output = root / OUTPUT
    try:
        current = normalize(output.read_text(encoding="utf-8"))
    except FileNotFoundError:
        current = None

    if args.check:
        if current is None:
            print(f"[gx-i18n] {OUTPUT} 缺失，运行 python scripts/gx_i18n.py 生成", file=sys.stderr)
            return 1
        if current != generated:
            print(
                f"[gx-i18n] {OUTPUT} 与 {UPSTREAM_PO}、{FORK_PO} 不一致，运行 python scripts/gx_i18n.py 重新生成",
                file=sys.stderr,
            )
            return 1
        print(f"[gx-i18n] {OUTPUT} 是最新的")
        return 0

    if current == generated:
        print(f"[gx-i18n] {OUTPUT} 无变化")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    with open(output, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(generated)
    print(f"[gx-i18n] 已写入 {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
